/**
 * Localized strings for DOCX / PDF export rendering.
 * Used in headers, footers, disclaimers and warnings inserted at the top of
 * the exported document.
 */

import type { Jurisdiction } from '@/lib/contracts/types'

export interface ExportStrings {
  /** Document footer "Generated by PrávníkAI" line */
  generatedBy: string
  /** Word for "Page" used in footers */
  page: string
  /** Word for "of" used in "Page X of Y" — leave empty to omit total */
  of: string
  /** Banner inserted at the top of a draft contract */
  draftBanner: string
  /** Tail of the draft banner — explanation in muted colour */
  draftBannerTail: string
  /** Banner inserted at the top of a review-needed contract */
  reviewBanner: string
  /** Tail of the review-needed banner */
  reviewBannerTail: string
  /** Footer label preceding the legal-basis citations */
  legalBasisPrefix: string
  /** End-of-document disclaimer body */
  disclaimer: string
  /** Locale tag for date formatting (e.g. cs-CZ, de-DE, en-GB) */
  dateLocale: string
}

export const EXPORT_STRINGS: Record<Jurisdiction, ExportStrings> = {
  CZ: {
    generatedBy: 'Vygenerováno: PrávníkAI',
    page: 'Strana',
    of: 'z',
    draftBanner: 'PRACOVNÍ NÁVRH',
    draftBannerTail: 'Text smlouvy určený k doplnění a právní kontrole před podpisem.',
    reviewBanner: 'VYŽADUJE KONTROLU',
    reviewBannerTail: 'Neúplná kostra. Před podpisem vyžaduje právní kontrolu.',
    legalBasisPrefix: 'Právní základ:',
    disclaimer:
      'Tento dokument byl vygenerován umělou inteligencí a slouží výhradně jako pracovní návrh. ' +
      'Před podpisem nebo právním použitím jej nechte zkontrolovat advokátem. Systém neposkytuje ' +
      'právní poradenství dle zák. č. 85/1996 Sb., o advokacii.',
    dateLocale: 'cs-CZ',
  },
  DE: {
    generatedBy: 'Erstellt mit: PrávníkAI',
    page: 'Seite',
    of: 'von',
    draftBanner: 'ARBEITSENTWURF',
    draftBannerTail: 'Vertragstext zur Ergänzung und juristischen Prüfung vor Unterzeichnung.',
    reviewBanner: 'PRÜFUNG ERFORDERLICH',
    reviewBannerTail: 'Unvollständiges Gerüst. Vor Unterzeichnung anwaltlich prüfen lassen.',
    legalBasisPrefix: 'Rechtsgrundlage:',
    disclaimer:
      'Dieses Dokument wurde durch künstliche Intelligenz erstellt und dient ausschließlich als ' +
      'Arbeitsentwurf. Vor Unterzeichnung oder rechtlicher Verwendung bitte anwaltlich prüfen lassen. ' +
      'Das System leistet keine Rechtsberatung im Sinne des Rechtsdienstleistungsgesetzes (RDG).',
    dateLocale: 'de-DE',
  },
  UK: {
    generatedBy: 'Generated by PrávníkAI',
    page: 'Page',
    of: 'of',
    draftBanner: 'WORKING DRAFT',
    draftBannerTail: 'Contract text to be completed and reviewed by a qualified solicitor before signature.',
    reviewBanner: 'REVIEW REQUIRED',
    reviewBannerTail: 'Indicative skeleton only. Solicitor review is required before any signature.',
    legalBasisPrefix: 'Legal basis:',
    disclaimer:
      'This document was generated by artificial intelligence and is provided solely as a working draft. ' +
      'Before signing or relying on it, please have it reviewed by a qualified solicitor. ' +
      'The system does not provide legal advice within the meaning of the Legal Services Act 2007.',
    dateLocale: 'en-GB',
  },
}

export function getExportStrings(jurisdiction: Jurisdiction): ExportStrings {
  return EXPORT_STRINGS[jurisdiction]
}

/** Format an ISO date string in the jurisdiction's preferred long format. */
export function formatExportDate(iso: string, jurisdiction: Jurisdiction): string {
  try {
    return new Date(iso).toLocaleDateString(EXPORT_STRINGS[jurisdiction].dateLocale, {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    })
  } catch {
    return iso
  }
}
